### PR TITLE
feat(#060): Add Terms and Privacy views

### PR DESCRIPTION
**Pull request by ezegonmac**
Add Terms and Privacy views.
Create footer component.
Move "Atención al cliente" to footer.

### CODE REVIEW

**Review by IsmaelP19 — CHANGES_REQUESTED** [review]
There is some problem with the styles showed in the product details view. The footer is centered and is not extended to the full width of the page.
image

**Review by TomasCB24 — CHANGES_REQUESTED** [review]
Everything correct except the page of details of a product, the footer does not extend completely.

**Comment by ezegonmac** [comment]
There was multiple unclosed html tags in base_DETAILS.html, so the footer was been placed in another container. Fixed 👍🏻

**Review by IsmaelP19 — APPROVED** [review]
Everything looks great now! Good job @ezegonmac 🎉🙌

**Review by TomasCB24 — APPROVED** [review]
Perfect. 👍🏼 💯 🥇

**Pull request merged**
