### PR TITLE
feat(#51): Add return policy

### PR DESCRIPTION
**Pull request by migromarj**
Add checkbox to accept the return policy before processing a payment. Add shipping costs to the total of a purchase.

### CODE REVIEW

**Review by juradosalado — APPROVED** [review]
Everything works fine. I guess shipping costs are always 0€.

**Review by TomasCB24 — APPROVED** [review]
It works well, just comment that it would still be necessary to leave a space between the check box and the text, but otherwise everything is correct.

**Comment by migromarj** [comment]
> Everything works fine. I guess shipping costs are always 0€.

Yes, they are always €0, he decided to make it static so that the user has the certainty that the shipping costs will not have costs.

**Comment by migromarj** [comment]
> It works well, just comment that it would still be necessary to leave a space between the check box and the text, but otherwise everything is correct.

Right, I'm going to remove that space and upload the change.

**Pull request merged**
