### PR TITLE
fix(#065): Fix security hotspots

### PR DESCRIPTION
**Pull request by ezegonmac**
Only fixed errors. For reviewing you should see web works as expected.

### CODE REVIEW

**Review by TomasCB24 — APPROVED** [review]
All works fine. Just change debug to true in development_settings.py.

**Comment by ezegonmac** [comment]
> All works fine. Just change debug to true in development_settings.py.



> All works fine. Just change debug to true in development_settings.py.

Fixed

**Review by IsmaelP19 — APPROVED** [review]
The only different thing I appreciate from main is the navbar. Now the cart button is narrower and it may not show correctly the number of items in the cart.
image

Apart form this, everything looks great! Good job 🙌🎉

**Comment by ezegonmac** [comment]
> The only different thing I appreciate from main is the navbar. Now the cart button is narrower and it may not show correctly the number of items in the cart. image
> 
> Apart form this, everything looks great! Good job 🙌🎉

This problem is from another pull request this is solved in another branch.

**Pull request merged**
